window.EIHRACAT_TODO_DATA = {
  "on-sartlar": [
    { id: "os-1", title: "İncelemeci kuruluş olarak kullanacağınız ihracatçı birliğini belirlemek", detail: "Destek başvuruları üye olunan ihracatçı birliği (incelemeci kuruluş) üzerinden yapılır; hangi birliğe üye olunacağını netleştirin." },
    { id: "os-2", title: "İhracatçı birliğine üyelik başvurusu yapmak", detail: "Seçilen ihracatçı birliğine resmî üyelik başvurusunda bulunun." },
    { id: "os-3", title: "Üyelik onayını almak ve üyelik belgesini saklamak", detail: "Üyelik onayı sonrası belgeyi başvurularda kullanmak üzere hazır tutun. DYS’de 'Birlik Üyelik Sorgulama' ile üyeliğinizi doğrulayabilirsiniz." },
    { id: "os-4", title: "DYS (Destek Yönetim Sistemi) portalına erişmek", detail: "dys.ticaret.gov.tr adresinden DYS’ye giriş yapın. Başvuru, üye olduğunuz İhracatçı Birliğine; üye değilseniz istediğiniz İhracatçı Birlikleri Genel Sekreterliğine yapılır." },
    { id: "os-5", title: "DYS yararlanıcı tanımlama belgelerini hazırlamak", detail: "DYS’ye kayıt için yararlanıcı tanımlama işlemlerinde istenen belgeleri hazırlayın; gerekli liste dys.ticaret.gov.tr Sıkça Sorulan Sorular bölümünde yer alır." },
    { id: "os-6", title: "DYS’de yararlanıcı (firma) kaydı oluşturmak", detail: "İhracatçı Birliğine başvurarak yararlanıcı tanımlama işleminizi yaptırın; sistemde şirketiniz kayıtlı hale getirilir (sadece ana şirket; şubeler için tanımlama yapılmaz)." },
    { id: "os-6b", title: "DYS kullanıcı yetkilendirme belgelerini hazırlamak", detail: "Sistemi sizin adınıza kullanacak kişiler için yetkilendirme belgeleri gerekir; DYS SSS’deki 'Kullanıcı Yetkilendirme İşlemleri için Gerekli Belgeler' linkinden listeyi indirin." },
    { id: "os-6c", title: "DYS kullanıcı yetkilendirmesini tamamlamak", detail: "Yararlanıcı tanımlaması sonrası, kullanıcı yetkilendirme sürecini tamamlayarak DYS’ye giriş yapabilecek kullanıcıları tanımlayın." },
    { id: "os-7", title: "MERSİS numarası ile kaydı eşleştirmek", detail: "DYS’de esas alınan tanımlayıcı MERSİS numarasıdır; MERSİS numarası ayrı olan her yararlanıcı ayrı tanımlanır." },
    { id: "os-7a", title: "NACE (faaliyet) kodunu güncellemek", detail: "MERSİS’te kayıtlı faaliyet kodunuzu e-ihracat/dijital ticaret ile uyumlu olacak şekilde güncelleyin." },
    { id: "os-8", title: "Yararlanıcı statüsünü tek olarak seçmek", detail: "Şirket, perakende e-ticaret sitesi, pazaryeri, B2B platformu veya E-İhracat Konsorsiyumu — sadece bir statü ile tüm desteklerden yararlanılır." },
    { id: "os-9", title: "Türk ürünü kriterini belgeleyecek üretim/tedarik sürecini netleştirmek", detail: "Üretimin tamamı veya bir bölümü Türkiye’de olmalı; süreci belgeleyebilecek şekilde kayıt tutun." },
    { id: "os-10", title: "Ürün ve platformda Türkiye üretim yeri bilgisini eklemek", detail: "Listeleme ve ürün sayfalarında KTÜN ve Türkiye’ye ait üretim yeri bilgisini kullanın." },
    { id: "os-11", title: "KTÜN/GTİN için TOBB bünyesindeki kuruluşa başvurmak", detail: "Ürün tanımlama numarası (KTÜN) almak üzere ilgili kuruluşa başvurun." },
    { id: "os-12", title: "KTÜN bilgisini ürün ve satış platformunda kullanmak", detail: "Alınan KTÜN’ü üründe ve platform listelemesinde göstermek zorunludur." },
    { id: "os-13", title: "Platform API/EDI dokümantasyonunu hazırlamak veya uzaktan erişim protokolünü kabul etmek", detail: "Destek alınacak platformlara ait API/EDI bilgisini incelemeci kuruluşa sunun; sunulamıyorsa Bakanlık/incelemeci kuruluşun uzaktan erişimine izin verin." },
    { id: "os-14", title: "Yurt içi marka tescilini yapmak veya tescil başvurusunda bulunmak", detail: "Desteğe konu ürünlerin markası yararlanıcı veya organik bağlı şirket adına; ilk tescil yurt içinde olmalı (istisna: Genelge 5/5)." },
    { id: "os-15", title: "Yurt dışı marka tescil başvurusu yapmak (hedef ülkelere göre)", detail: "Gerekiyorsa yurt dışı marka tescil sürecini başlatın." },
    { id: "os-16", title: "Platform hesaplarının şirket veya organik bağlı şirket adına olduğunu doğrulamak", detail: "Destek harcamalarının yapılacağı platformların hesap yönetimi başvuru sahibi veya organik bağlı şirket üzerinden olmalı." },
    { id: "os-17", title: "Organik bağ varsa %51+ ortaklık ve kuruluş sırası belgesini hazırlamak", detail: "Yurt dışı harcama yapan şirket varsa en az %51 ortaklık; yurt dışı şirket yararlanıcıdan sonra kurulmuş olmalı (istisnalar Genelge’de)." },
    { id: "os-18", title: "İlişkili kişi çatışması olmadığını kontrol etmek", detail: "Harcamayı yapan ile faturayı düzenleyen taraf ilişkili kişi olmamalı (ortaklar, yönetim/denetim, eşler, hısımlar vb.)." },
    { id: "os-19", title: "Listeleme ve tanıtımda Türkiye imajına uygunluk kontrolü yapmak", detail: "Ürün içeriklerinde 'Türkiye' ifadesi kullanın; tanıtımda ülke imajına zarar vermeyin." },
    { id: "os-20", title: "5986 sayılı Karar ve Karara İlişkin Genelge'yi okumak", detail: "ticaret.gov.tr/destekler/e-ihracat-destekleri sayfasından '5986 Sayılı E-İhracat Destekleri Hakkında Karar' ile 'Karara İlişkin Genelge' metinlerini indirip inceleyin." },
    { id: "os-20b", title: "Genelge ekleri ve destek üst limitleri sayfasını incelemek", detail: "ticaret.gov.tr e-ihracat destekleri sayfasındaki 'Genelge Ekleri ve Destek Üst Limitleri' bölümünden güncel formları ve her destek türü için üst limitleri kontrol edin." },
    { id: "os-21", title: "KEP ve e-imza usulünü öğrenmek; KEP kullanımını başlatmak", detail: "Başvurular KEP üzerinden yapılır; ticaret.gov.tr 'KEP ve E-İmza Usulü Hakkında' sayfasını okuyup KEP hesabı edinin." },
    { id: "os-22", title: "DYS ve e-ihracat kılavuzlarını incelemek", detail: "dys.ticaret.gov.tr 'Kılavuzlar ve Dikkat Edilecek Hususlar' ile ticaret.gov.tr e-ihracat destekleri sayfasındaki 'Kılavuzlar' bölümünü okuyun." },
    { id: "os-23", title: "İhtiyaç halinde destek kanallarını bilmek (Kolay Destek, Uzmana/Müşavire Danışın)", detail: "Kolay Destek (kolaydestek.gov.tr), Kolay İhracat Platformu (kolayihracat.gov.tr), DYS Uzmana/Müşavire Danışın ve Birliklere Danışın (TİM) seçenekleri mevcuttur." },
    { id: "os-24", title: "E-İhracat Destekleri sunumları ve eğitim videolarını izlemek (isteğe bağlı)", detail: "ticaret.gov.tr e-ihracat destekleri sayfasındaki 'E-İhracat Destekleri Sunumları ve Eğitim Videoları' ile 'Yeni Nesil İhracat Destekleri ve Prefinansman Modeli' tanıtımını izleyin." }
  ],
  "kapsama": [
    { id: "ka-1", title: "Şirket: Kapsama alınma başvuru formunu doldurmak", detail: "Şirket Başvuru Formu; incelemeci kuruluşa (ihracatçı birliği) sunulacak." },
    { id: "ka-2", title: "Şirket: Marka tescil veya tescil başvuru belgesini eklemek", detail: "Desteğe konu ürünlerin marka tescil/başvuru belgesi eklenir." },
    { id: "ka-3", title: "Şirket: Ortaklık yapısı, KTÜN ve kapasite raporu/tedarikçi belgelerini hazırlamak", detail: "Marka tescil bilgileri formu ile birlikte başvuruya eklenir." },
    { id: "ka-4", title: "Şirket: Kooperatif ise üyeler listesi ve faaliyet belgesi almak", detail: "Ticaret il müdürlükleri veya TSO’dan kooperatif faaliyet bilgi/belgesi alınır." },
    { id: "ka-5", title: "Şirket: Organik bağ varsa yurt dışı şirket kuruluş/sermaye belgesi hazırlamak", detail: "İlgili ülke ticaret sicili, hazirun cetveli vb.; Bakanlık yurt dışı temsilcisi onayı gerekebilir." },
    { id: "ka-6", title: "Şirket: Kapsama başvurusunu incelemeci kuruluşa KEP ile iletmek", detail: "Eksiksiz belgelerle başvuruyu tamamlayıp iletilmesi." },
    { id: "ka-7", title: "Perakende e-ticaret sitesi: Kriterleri kontrol etmek (hasılat, marka, 2 yıl, güven damgası, eşik)", detail: "Satış hasılatının en az 2/3’ü çevrim içi; kendi/organik bağlı marka ağırlığı en az 1/4; 2 takvim yılı faaliyet; 1.000.000 USD ihracat veya ETBİS eşiği." },
    { id: "ka-8", title: "Perakende e-ticaret sitesi: Kapsama başvurusunu E-İhracat Sekretaryasına yapmak", detail: "Güven damgası veya eşdeğer belge ile birlikte başvuru." },
    { id: "ka-9", title: "Pazaryeri: Kriterleri kontrol etmek (2 yıl, hizmet sağlayıcı, ürün sayısı, eşik)", detail: "2 takvim yılı faaliyet; sipariş karşılama istasyonu veya iş ortaklığı; en az 1.000 hizmet sağlayıcı ve 100.000 ürün; 5.000.000 USD ihracat veya ETBİS eşiği." },
    { id: "ka-10", title: "Pazaryeri: Kapsama başvurusunu E-İhracat Sekretaryasına yapmak", detail: "Güven damgası veya eşdeğer belge ile başvuru." },
    { id: "ka-11", title: "B2B platformu: Kriterleri kontrol edip kapsama başvurusu yapmak", detail: "2 takvim yılı faaliyet; B2B sipariş imkânı; en az 1.000 ücretli üye; Türkiye E-İhracat Platformu ile iş birliği; E-İhracat Sekretaryasına başvuru." },
    { id: "ka-12", title: "E-İhracat Konsorsiyumu: Statü başvurusunu Bakanlığa yapmak", detail: "E-İhracat Konsorsiyumu Statüsüne İlişkin Genelge hükümlerine göre Bakanlıkça statü verilir." }
  ],
  "pazaryeri-hesaplari": [
    { id: "ph-1", title: "Destek kapsamındaki pazaryeri listesini (Bakanlık/DYS) incelemek", detail: "Dijital pazaryeri tanıtım ve komisyon desteği verilen pazaryerleri Bakanlık/Genelge listesinde yer alır; listeyi ticaret.gov.tr veya incelemeci kuruluştan alın." },
    { id: "ph-2", title: "Hedef ülkelere göre hangi pazaryerlerinde hesap açılacağını belirlemek", detail: "Hedef ülkelerde (ABD, AB, Çin, vb.) faaliyet gösteren ve destek kapsamındaki pazaryerlerini seçin; hedef ülkede faaliyet birçok destekte +20 puan sağlar." },
    { id: "ph-3", title: "Seçilen her pazaryeri için hesap açılış gereksinimlerini (belgeler, ücret) listelemek", detail: "Amazon, eBay, Etsy, Alibaba, Trendyol Global vb. her platformun satıcı kayıt sayfasından gerekli belgeleri (şirket bilgisi, vergi no, banka, kimlik) ve ücretleri not edin." },
    { id: "ph-4", title: "Pazaryeri satıcı kayıt sayfasından başvuru başlatmak", detail: "Platformun resmî satıcı/seller kayıt sayfasına gidip kayıt formunu doldurmaya başlayın; hesap şirket veya organik bağlı şirket adına olmalı." },
    { id: "ph-5", title: "Şirket bilgileri, vergi numarası ve banka/ödeme bilgilerini girmek", detail: "Yararlanıcı veya organik bağlı şirketin ticaret unvanı, MERSİS, vergi no ve ödeme alacağı banka/hesap bilgilerini platforma girin." },
    { id: "ph-6", title: "Kimlik/yetki belgesi ve gerekirse ticaret sicil belgesi yüklemek", detail: "Platformun istediği yetkili kimlik ve şirket belgelerini yükleyin; bazı pazaryerleri ticaret sicil özeti ister." },
    { id: "ph-7", title: "Hesap doğrulama ve onay sürecini tamamlamak", detail: "E-posta/telefon doğrulama, bazen video görüşme veya ek belge talebi; onay gelene kadar takip edin." },
    { id: "ph-8", title: "Açılan hesabı DYS ve incelemeci kuruluş bilgilerinde tutmak", detail: "Hangi pazaryerinde hesap açıldığını, açılış tarihini ve hesap bilgilerini destek başvurularında kullanmak üzere kaydedin." },
    { id: "ph-9", title: "Açılan hesap için dijital pazaryeri tanıtım desteği ön başvurusu yapmak", detail: "Destek almak istediğiniz pazaryerini ve harcama planını belirleyip ön onay başvurusunu incelemeci kuruluşa iletin; ön onay sonrası harcama yapın." },
    { id: "ph-10", title: "Aynı hesap için pazaryeri komisyon gideri desteği ön başvurusu (uygunsa) yapmak", detail: "Komisyon desteği verilen ülke/pazaryeri listesine uygunsa, ilgili pazaryeri hesabı için komisyon desteği ön onayı alın." },
    { id: "ph-11", title: "Ön onay aldıktan sonra tanıtım/komisyon harcamalarını yapıp belgeleri saklamak", detail: "Ön onaylı tutar ve dönem içinde harcama yapın; fatura ve belgeleri çeyrek dönem ödeme başvurusu için 6 ay kuralına uygun şekilde toplayın." }
  ],
  "destekler": [
    { id: "de-1", title: "Pazara giriş rapor desteği: Başvuru formu ve eklerini hazırlamak", detail: "İlgili form ve ekleri incelemeci kuruluşa sunmak üzere hazırlayın." },
    { id: "de-2", title: "Pazara giriş rapor desteği: Ön onay başvurusunu incelemeci kuruluşa iletmek", detail: "Ön onay sonrası harcamalar yapılır; ön onay almadan harcama yapmayın." },
    { id: "de-3", title: "Pazara giriş rapor desteği: Ön onay sonrası harcamaları yapmak ve belgeleri toplamak", detail: "Harcama belgeleri ödeme başvurusu için saklanır." },
    { id: "de-4", title: "Pazara giriş rapor desteği: Destek ödeme başvurusunu belge tarihinden itibaren 6 ay içinde yapmak", detail: "Harcama belgeleri ile incelemeci kuruluşa ödeme başvurusu." },
    { id: "de-5", title: "Dijital pazaryeri tanıtım desteği: Pazaryeri/kanal ve harcama planını hazırlamak", detail: "Destek limiti dahilinde; hedef ülkelerde +20 puan uygulanır." },
    { id: "de-6", title: "Dijital pazaryeri tanıtım desteği: Ön onay başvurusu yapmak", detail: "İncelemeci kuruluşa ön onay başvurusu iletin." },
    { id: "de-7", title: "Dijital pazaryeri tanıtım desteği: Çeyrek dönem harcama belgelerini toplamak", detail: "Ocak–Mart, Nisan–Haziran, Temmuz–Eylül, Ekim–Aralık dönemleri." },
    { id: "de-8", title: "Dijital pazaryeri tanıtım desteği: Ödeme başvurusunu 6 ay kuralına uygun yapmak", detail: "Belge tarihinden itibaren en geç 6 ay içinde başvuru." },
    { id: "de-9", title: "E-İhracat tanıtım desteği: Tanıtım kanalları ve harcama planını hazırlamak", detail: "Hedef ülkelerde +20 puan; ön onay için plan gerekli." },
    { id: "de-10", title: "E-İhracat tanıtım desteği: Ön onay başvurusu yapmak", detail: "İncelemeci kuruluşa ön onay başvurusu." },
    { id: "de-11", title: "E-İhracat tanıtım desteği: Çeyrek dönem belgeleri ile ödeme başvurusu (6 ay içinde)", detail: "Ödeme belge tarihinden itibaren en geç 6 ay." },
    { id: "de-12", title: "Sipariş karşılama hizmeti desteği: Bakanlık listesinden hizmet sağlayıcı seçmek", detail: "Sipariş karşılama hizmeti veren listeden seçim; depolama + birim sipariş karşılama gideri; hedef ülkelerde +20 puan." },
    { id: "de-13", title: "Sipariş karşılama hizmeti desteği: Ön onay başvurusu yapmak", detail: "İncelemeci kuruluşa ön onay başvurusu." },
    { id: "de-14", title: "Sipariş karşılama hizmeti desteği: Çeyrek dönem belgeleri ile ödeme başvurusu (6 ay içinde)", detail: "6 ay kuralına uygun ödeme başvurusu." },
    { id: "de-15", title: "Depo kira desteği: Ön onay başvurusu yapmak", detail: "Depo kira desteği için incelemeci kuruluşa ön onay başvurusu." },
    { id: "de-16", title: "Depo kira desteği: Deponun yerinde incelemesine izin vermek", detail: "Yerinde inceleme sonrası uygunluk onayı alınır." },
    { id: "de-17", title: "Depo kira desteği: Yarım dönem (Ocak–Haziran / Temmuz–Aralık) belgeleri ile ödeme başvurusu", detail: "Belge tarihinden itibaren en geç 6 ay içinde başvuru." },
    { id: "de-18", title: "Yurt dışı pazaryeri entegrasyon desteği: Entegrasyon kapsamı ve harcama planı hazırlamak", detail: "Hedef ülke ilave puanı uygulanmaz; ön onay için plan gerekli." },
    { id: "de-19", title: "Yurt dışı pazaryeri entegrasyon desteği: Ön onay ve ardından ödeme başvurusu (6 ay kuralı)", detail: "Çeyrek dönem belgeleri ile 6 ay içinde ödeme başvurusu." },
    { id: "de-20", title: "Çevrim içi mağaza ve hedef ülke paydaşları hizmet desteği: Ülke ve hizmet kapsamını belirlemek", detail: "Belirlenen ülkelere (Çin, Hindistan, Japonya, Brezilya) yönelik hizmetler; ön onay sonrası harcama." },
    { id: "de-21", title: "Çevrim içi mağaza ve hedef ülke paydaşları: Ön onay ve çeyrek dönem ödeme başvurusu (6 ay)", detail: "Çeyrek dönem belgeleri; 6 ay kuralı." },
    { id: "de-22", title: "Pazaryeri komisyon gideri desteği: Desteklenecek ülke/pazaryeri listesine uygunluğu kontrol etmek", detail: "Hedef ülkelerde +20 puan; listeye uygunluk şart." },
    { id: "de-23", title: "Pazaryeri komisyon gideri desteği: Ön onay ve çeyrek dönem komisyon belgeleri ile ödeme (6 ay)", detail: "6 ay kuralına uygun ödeme başvurusu." },
    { id: "de-24", title: "Genel: Türk ürünü satış oranına göre destek hesaplandığını bilmek", detail: "Destekler Türk ürünü satış oranına göre hesaplanır; üst limitler Genelge’de belirtilir." },
    { id: "de-25", title: "Harcama ve ödeme belgelerini DYS usulüne uygun tutmak", detail: "Faturalar, sözleşmeler, dekontlar ve diğer belgeler DYS’deki 'Harcama ve Ödeme Belgelerinin Yönetilmesi' ve künye havuzu kurallarına uygun saklanmalı; üçüncü taraflar dysbg.ticaret.gov.tr ile belge doğrulama yapabilir." }
  ],
  "yillik": [
    { id: "yi-1", title: "E-İhracat Değerlendirme Beyanı formunu hazırlamak", detail: "Her takvim yılı için bir sonraki yılın Nisan ayının ilk iş gününe kadar sunulacak." },
    { id: "yi-2", title: "E-İhracat Değerlendirme Beyanını incelemeci kuruluşa sunmak", detail: "E-İhracat Sekretaryasına iletilmek üzere incelemeci kuruluşa verilir." },
    { id: "yi-3", title: "Ortaklık yapısı değiştiyse: Değişiklik tarihinden itibaren 1 ay içinde DYS’ye bildirmek", detail: "Ortaklık oranı veya 6563 sayılı Kanun kapsamında ekonomik bütünlük değişirse bilgi ve belge yüklenir." },
    { id: "yi-4", title: "Ödeme başvuruları için 6 ay kuralını takip etmek", detail: "Her destek türünde ödeme belge tarihinden itibaren en geç 6 ay içinde ilgili ödeme başvurusu incelemeci kuruluşa yapılmalı." },
    { id: "yi-5", title: "Çeyrek/yarım dönem takvimi oluşturmak (Ocak–Mart, Nisan–Haziran vb.)", detail: "Hangi dönemde hangi destek için ödeme başvurusu yapılacağını planlayın; 6 ayı aşmayın." },
    { id: "yi-6", title: "DYS ve ticaret.gov.tr e-ihracat duyurularını takip etmek", detail: "dys.ticaret.gov.tr ile ticaret.gov.tr/destekler/e-ihracat-destekleri duyurularını (E-Kolay İhracat, İhracat Akademisi, E-İhracat Organizasyonları/Konferanslar, mevzuat güncellemeleri) düzenli kontrol edin." }
  ]
};
